# Generated by Django 6.0.5 on 2026-05-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classassignment_id_alter_classnotice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='classassignment',
            name='students',
            field=models.ManyToManyField(related_name='student_assignments', to='classroom.student'),
        ),
    ]
